title: EMUS
baseurl: ""
url: ""
markdown: kramdown
theme: null
plugins: []
permalink: pretty
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - README.md
  - AGENTS.md
  - STYLE.md
  - SPEC.md
